from sqlalchemy import Column, String, Float, Integer
from backend.models.stock import Base

class DailyData(Base):
    __tablename__ = "daily_data"
    code = Column(String, primary_key=True)
    date = Column(String, primary_key=True)
    close = Column(Float)
    ma5 = Column(Float)
    ma13 = Column(Float)
    ma30 = Column(Float)
    macd_dif = Column(Float)
    macd_dea = Column(Float)
    macd_bar = Column(Float)
    rsi14 = Column(Float)
    kdj_k = Column(Float)
    kdj_d = Column(Float)
    kdj_j = Column(Float)
    boll_upper = Column(Float)
    boll_mid = Column(Float)
    boll_lower = Column(Float)
    volume_ratio = Column(Float)
    main_inflow_today = Column(Float)
    main_inflow_5d = Column(Float)
    super_large_inflow = Column(Float)
    north_inflow = Column(Float)
    margin_net_buy = Column(Float)
    pe = Column(Float)
    pb = Column(Float)
    roe = Column(Float)
    profit_growth_yoy = Column(Float)
    market_cap = Column(Float)
    report_count = Column(Integer)
    report_rating = Column(String)
    announcement_type = Column(String)
    news_sentiment = Column(Float)
    change_pct = Column(Float)
    turnover_rate = Column(Float)
    consecutive_limit_up = Column(Integer, default=0)
    sector_heat_rank = Column(Integer)
